apiVersion: v1
kind: Secret
metadata:
  name: minio-backup
  labels: !Var secret_labels
type: Opaque
data:
  accessKeyId: !Base64,Var minio_access_key_id
  secretAccessKey: !Base64,Var minio_secret_access_key
